apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http # Matches the 'name' of the containerPort in the deployment
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}