replicaCount: 2

image:
  # The image repository path. This should match your Artifact Registry URL.
  repository: us-central1-docker.pkg.dev/mando-service-project-1/docker-repo/my-app
  pullPolicy: IfNotPresent
  # The image tag. Use "latest" to always deploy the newest image.
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi